#!/bin/bash
# QUICK_REFERENCE_HF_MIGRATION.sh
# Quick commands for Hugging Face migration

echo "🚀 HUGGING FACE MIGRATION - QUICK REFERENCE"
echo "=============================================="
echo ""

# 1. SETUP
echo "1️⃣  SETUP"
echo "────────────────"
echo "# Install dependencies"
echo "pip install -r requirements.txt"
echo ""
echo "# Get API key: https://huggingface.co/settings/tokens"
echo "export HF_API_KEY='hf_your_token_here'"
echo ""

# 2. VALIDATION
echo "2️⃣  VALIDATION"
echo "────────────────"
echo "# Test HF integration"
echo "python test_hf_migration.py"
echo ""
echo "# Expected: 7/7 tests passed ✅"
echo ""

# 3. LOCAL TESTING
echo "3️⃣  LOCAL TESTING"
echo "────────────────"
echo "# Test RAG system"
echo "python scripts/test_rag_system.py"
echo ""
echo "# Generate flashcards"
echo "python scripts/generate_flashcards.py --limit 1"
echo ""
echo "# Generate summaries"
echo "python scripts/generate_summaries.py --limit 1"
echo ""
echo "# Start frontend"
echo "streamlit run frontend/streamlit_app.py"
echo ""

# 4. PROVIDER SELECTION
echo "4️⃣  PROVIDER SELECTION"
echo "────────────────"
echo "# Use Hugging Face (default)"
echo "# config.yaml:"
echo "# provider: 'huggingface'"
echo "# model: 'mistralai/Mistral-7B-Instruct'"
echo ""
echo "# OR in Python:"
echo "from src.llm.llm_loader import LLMConfig, load_llm"
echo "config = LLMConfig(provider='huggingface')"
echo "llm = load_llm(config)"
echo ""
echo "# Use Groq (alternative)"
echo "config = LLMConfig(provider='groq')"
echo ""
echo "# Use Ollama (local, deprecated)"
echo "config = LLMConfig(provider='ollama')"
echo ""

# 5. CLOUD DEPLOYMENT
echo "5️⃣  CLOUD DEPLOYMENT"
echo "────────────────"
echo "# Render.com (Recommended - 5 min setup)"
echo "git push origin main"
echo "# Then in Render dashboard:"
echo "#   - Select repo"
echo "#   - Set HF_API_KEY env var"
echo "#   - Auto-deploys!"
echo ""
echo "# Railway.app (Similar setup)"
echo "railway login"
echo "railway variables set HF_API_KEY=hf_..."
echo "railway up"
echo ""
echo "# Google Cloud Run (with Docker)"
echo "docker build -t speech-rag ."
echo "gcloud run deploy speech-rag --source . \\"
echo "  --set-env-vars=HF_API_KEY=hf_..."
echo ""

# 6. ENVIRONMENT VARIABLES
echo "6️⃣  ENVIRONMENT VARIABLES"
echo "────────────────"
echo "# Set HF API key (choose one method)"
echo ""
echo "# Method 1: Export"
echo "export HF_API_KEY='hf_your_token_here'"
echo ""
echo "# Method 2: .env file"
echo "# Create file: .env"
echo "# Add: HF_API_KEY=hf_your_token_here"
echo "# Never commit .env!"
echo ""
echo "# Method 3: Cloud dashboard"
echo "# Set in Render/Railway/GCP console"
echo ""

# 7. TROUBLESHOOTING
echo "7️⃣  TROUBLESHOOTING"
echo "────────────────"
echo "# Check API key"
echo "echo \$HF_API_KEY"
echo ""
echo "# View config"
echo "cat config/config.yaml | grep -A 5 llm:"
echo ""
echo "# Test API connection"
echo "python -c \"from huggingface_hub import InferenceClient; c = InferenceClient(token='hf_...')\""
echo ""
echo "# Check logs (Render)"
echo "# Settings → Logs"
echo ""
echo "# Common errors:"
echo "# - 'Invalid API key' → Check HF_API_KEY"
echo "# - 'Rate limited' → Wait or upgrade HF account"
echo "# - 'Model not found' → Check config.yaml"
echo "# - 'ImportError' → pip install huggingface_hub"
echo ""

# 8. DOCUMENTATION
echo "8️⃣  DOCUMENTATION"
echo "────────────────"
echo "# Read guides"
echo "cat HF_MIGRATION_GUIDE.md"
echo "cat CLOUD_DEPLOYMENT_GUIDE.md"
echo "cat MIGRATION_SUMMARY.md"
echo "cat COMPLETION_CHECKLIST.md"
echo ""

# 9. MONITORING
echo "9️⃣  MONITORING"
echo "────────────────"
echo "# Check deployment status (Render)"
echo "# Dashboard → Service → Status"
echo ""
echo "# View logs"
echo "# Dashboard → Service → Logs (tail -f)"
echo ""
echo "# Test endpoint"
echo "curl https://your-app.onrender.com"
echo ""

# 10. ROLLBACK (if needed)
echo "🔟 ROLLBACK"
echo "────────────────"
echo "# To temporarily use Ollama:"
echo "# 1. Start Ollama server: ollama serve"
echo "# 2. In config.yaml or code:"
echo "#    provider: 'ollama'"
echo "#    model: 'llama3'"
echo ""
echo "# Note: HF is default and recommended"
echo ""

echo ""
echo "=============================================="
echo "📚 Full docs: HF_MIGRATION_GUIDE.md"
echo "🚀 Deploy: CLOUD_DEPLOYMENT_GUIDE.md"
echo "✅ Status: COMPLETION_CHECKLIST.md"
echo "🌐 Resources:"
echo "    - HF API: https://huggingface.co/docs/hub/inference-api"
echo "    - Render: https://render.com/docs"
echo "    - Railway: https://railway.app/docs"
echo "=============================================="
